using System;
using System.Collections.Generic;

namespace RazorEnhanced
{
    internal static class HotKeyDisplayNames
    {
        private static readonly Dictionary<string, string> m_names = new(StringComparer.Ordinal)
        {
            { "Resync", "重新同步" },
            { "Take Screen Shot", "屏幕截图" },
            { "Start Video Record", "开始录像" },
            { "Stop Video Record", "停止录像" },
            { "Ping Server", "检测服务器延迟" },
            { "Accept Party", "接受队伍邀请" },
            { "Decline Party", "拒绝队伍邀请" },
            { "DPS Meter Start", "启动伤害统计" },
            { "DPS Meter Pause / Resume", "暂停/继续伤害统计" },
            { "DPS Meter Pause", "暂停伤害统计" },
            { "No Run Stealth ON/OFF", "潜行禁止奔跑 开/关" },
            { "Open Enhanced Map", "打开增强地图" },
            { "Inspect Item/Ground", "检查物品/地面" },

            { "Grab Item", "抓取物品" },
            { "Drop Item", "放下物品" },
            { "Fly ON/OFF", "飞行 开/关" },
            { "Hide Item", "隐藏物品" },
            { "Last Item", "上次物品" },
            { "Left Hand", "左手物品" },
            { "Right Hand", "右手物品" },
            { "All", "全部" },
            { "Corpses", "尸体" },
            { "Mobiles", "生物" },
            { "Items", "物品" },

            { "All Come", "全部跟来" },
            { "All Follow Me", "全部跟随我" },
            { "All Follow", "全部跟随目标" },
            { "All Guard Me", "全部保护我" },
            { "All Guard", "全部保护目标" },
            { "All Kill", "全部攻击" },
            { "All Stay", "全部停留" },
            { "All Stop", "全部停止" },
            { "Mount", "上骑" },
            { "Dismount", "下骑" },
            { "Mount / Dismount", "上骑/下骑" },

            { "Autoloot Trigger ON/OFF", "自动拾取 开/关" },
            { "Autoloot Set Bag", "设置自动拾取容器" },
            { "Autoloot Add Item", "添加自动拾取物品" },
            { "Scavenger Trigger ON/OFF", "拾荒 开/关" },
            { "Scavenger Set Bag", "设置拾荒容器" },
            { "Scavenger Add Item", "添加拾荒物品" },
            { "Organizer Start", "开始整理" },
            { "Organizer Stop", "停止整理" },
            { "Organizer Set Source Bag", "设置整理来源容器" },
            { "Organizer Set Destination Bag", "设置整理目标容器" },
            { "Organizer Add Item", "添加整理物品" },
            { "Sell Trigger ON/OFF", "出售代理 开/关" },
            { "Sell Set Source Bag", "设置出售来源容器" },
            { "Buy Trigger ON/OFF", "购买代理 开/关" },
            { "Dress Start", "开始穿戴" },
            { "Undress Start", "开始脱装" },
            { "Dress / Undress Stop", "停止穿戴/脱装" },
            { "Restock Start", "开始补货" },
            { "Restock Stop", "停止补货" },
            { "Restock Set Source Bag", "设置补货来源容器" },
            { "Restock Set Destination Bag", "设置补货目标容器" },
            { "Restock Add Item", "添加补货物品" },
            { "Bandage Heal Trigger ON/OFF", "绷带治疗 开/关" },
            { "Bone Cutter Trigger ON/OFF", "自动切骨 开/关" },
            { "Bone Cutter Set Blade", "设置切骨刀具" },
            { "Auto Carver Trigger ON/OFF", "自动切尸 开/关" },
            { "Auto Carver Set Blade", "设置切尸刀具" },
            { "Auto Remount Trigger ON/OFF", "自动上骑 开/关" },
            { "Auto Remount Set Mount", "设置坐骑" },
            { "Graphic Filter Trigger ON/OFF", "图像过滤 开/关" },
            { "Add Friend", "添加好友" },

            { "Primary", "主要武器能力" },
            { "Secondary", "次要武器能力" },
            { "Primary ON/OFF", "主要武器能力 开/关" },
            { "Secondary ON/OFF", "次要武器能力 开/关" },
            { "Stun", "击晕" },
            { "Disarm", "缴械" },
            { "Cancel", "取消能力" },
            { "Attack Last", "攻击上个对象" },
            { "Attack Last Target", "攻击上个目标" },
            { "WarMode ON/OFF", "战斗模式 开/关" },
            { "Self", "自己" },
            { "Last", "上个目标" },
            { "Use Only", "仅使用绷带" },
            { "Clear Left", "清空左手" },
            { "Clear Right", "清空右手" },
            { "Equip Left", "装备左手" },
            { "Equip Right", "装备右手" },
            { "Toggle Left", "切换左手装备" },
            { "Toggle Right", "切换右手装备" },

            { "Potion Agility", "敏捷药水" },
            { "Potion Cure", "解毒药水" },
            { "Potion Explosion", "爆炸药水" },
            { "Potion Heal", "治疗药水" },
            { "Potion Nightsight", "夜视药水" },
            { "Potion Refresh", "体力恢复药水" },
            { "Potion Strength", "力量药水" },
            { "Potion Invisibility", "隐形药水" },
            { "Potion Confusion Blast", "混乱爆破药水" },
            { "Potion Conflagration", "燃烧药水" },
            { "Potion Parasitic", "寄生药水" },
            { "Potion Darkglow Poison", "暗光毒药水" },
            { "Potion Shatter", "粉碎药水" },
            { "Potion Exploding Tar", "爆裂焦油药水" },
            { "Potion Fear Essence", "恐惧精华药水" },
            { "Potion Sakkhra Prophylaxis", "萨卡拉预防药水" },
            { "Potion Supernova", "超新星药水" },
            { "Darkglow Poison", "暗光毒药" },
            { "Barako Draft Of Might", "巴拉科力量药剂" },
            { "Jukari Burn Poultice", "朱卡里灼伤膏" },
            { "Kurak Ambusher's Essence", "库拉克伏击者精华" },
            { "Fear Essence", "恐惧精华" },
            { "Urali Trance Tonic", "乌拉里恍惚药剂" },
            { "Enchanted Apple", "附魔苹果" },
            { "Orange Petals", "橙色花瓣" },
            { "Rose Of Trinsic", "特林西克玫瑰" },
            { "Pouch", "小袋" },
            { "Wrath Grapes", "愤怒葡萄" },
            { "Smoke Bomb", "烟雾弹" },
            { "Healing Stone", "治疗石" },
            { "Spell Stone", "法术石" },

            { "Wand Clumsy", "笨拙法杖" },
            { "Wand Feeblemind", "弱智法杖" },
            { "Wand Fireball", "火球法杖" },
            { "Wand Greater Heal", "强力治疗法杖" },
            { "Wand Harm", "伤害法杖" },
            { "Wand Heal", "治疗法杖" },
            { "Wand Identification", "鉴定法杖" },
            { "Wand Lightning", "闪电法杖" },
            { "Wand Magic Arrow", "魔法箭法杖" },
            { "Wand Mana Drain", "法力吸取法杖" },
            { "Wand Weakness", "虚弱法杖" },

            { "Anatomy", "解剖学" },
            { "Animal Lore", "动物知识" },
            { "Animal Taming", "驯兽" },
            { "Arms Lore", "武器知识" },
            { "Begging", "乞讨" },
            { "Cartography", "制图" },
            { "Detect Hidden", "侦测隐藏" },
            { "Discordance", "挑拨不和" },
            { "Eval Int", "智力评估" },
            { "Forensics", "法医学" },
            { "Hiding", "隐藏" },
            { "Imbuing", "灌输" },
            { "Inscribe", "抄写" },
            { "Item ID", "物品鉴定" },
            { "Last Used", "上次使用技能" },
            { "Meditation", "冥想" },
            { "Peacemaking", "和平" },
            { "Provocation", "煽动" },
            { "RemoveTrap", "拆除陷阱" },
            { "Spirit Speak", "灵魂沟通" },
            { "Stealing", "偷窃" },
            { "Stealth", "潜行" },
            { "Taste ID", "味觉鉴定" },
            { "Tracking", "追踪" },

            { "Last Spell", "上次法术" },
            { "Last Spell Last Target", "上次法术攻击上个目标" },
            { "Interrupt", "打断施法" },
            { "Mini Heal", "小治疗" },
            { "Big Heal", "大治疗" },
            { "Chivarly Heal", "骑士治疗" },

            { "Clumsy", "笨拙" },
            { "Create Food", "创造食物" },
            { "Feeblemind", "弱智" },
            { "Heal", "治疗" },
            { "Magic Arrow", "魔法箭" },
            { "Night Sight", "夜视" },
            { "Reactive Armor", "反应护甲" },
            { "Weaken", "虚弱" },
            { "Agility", "敏捷" },
            { "Cunning", "狡猾" },
            { "Cure", "解毒" },
            { "Harm", "伤害" },
            { "Magic Trap", "魔法陷阱" },
            { "Magic Untrap", "解除魔法陷阱" },
            { "Protection", "保护" },
            { "Strength", "力量" },
            { "Bless", "祝福" },
            { "Fireball", "火球" },
            { "Magic Lock", "魔法锁" },
            { "Poison", "中毒" },
            { "Telekinesis", "心灵遥控" },
            { "Teleport", "传送" },
            { "Unlock", "开锁" },
            { "Wall of Stone", "石墙" },
            { "Arch Cure", "群体解毒" },
            { "Arch Protection", "群体保护" },
            { "Curse", "诅咒" },
            { "Fire Field", "火墙" },
            { "Greater Heal", "强力治疗" },
            { "Lightning", "闪电" },
            { "Mana Drain", "法力吸取" },
            { "Recall", "回忆" },
            { "Blade Spirits", "刀锋精灵" },
            { "Dispel", "驱散" },
            { "Incognito", "伪装" },
            { "Magic Reflection", "魔法反射" },
            { "Mind Blast", "心灵爆破" },
            { "Paralyze", "麻痹" },
            { "Poison Field", "毒墙" },
            { "Summon Creature", "召唤生物" },
            { "Dispel Field", "驱散力场" },
            { "Energy Bolt", "能量箭" },
            { "Explosion", "爆炸" },
            { "Invisibility", "隐形" },
            { "Mark", "标记" },
            { "Mass Curse", "群体诅咒" },
            { "Paralyze Field", "麻痹力场" },
            { "Reveal", "揭露" },
            { "Chain Lightning", "连锁闪电" },
            { "Energy Field", "能量力场" },
            { "Flamestrike", "烈焰冲击" },
            { "Gate Travel", "传送门" },
            { "Mana Vampire", "法力吸血" },
            { "Mass Dispel", "群体驱散" },
            { "Meteor Swarm", "流星雨" },
            { "Polymorph", "变形" },
            { "Earthquake", "地震" },
            { "Energy Vortex", "能量漩涡" },
            { "Resurrection", "复活" },
            { "Summon Air Elemental", "召唤空气元素" },
            { "Summon Daemon", "召唤恶魔" },
            { "Summon Earth Elemental", "召唤土元素" },
            { "Summon Fire Elemental", "召唤火元素" },
            { "Summon Water Elemental", "召唤水元素" },

            { "Animate Dead", "操纵尸体" },
            { "Blood Oath", "血誓" },
            { "Corpse Skin", "尸皮" },
            { "Curse Weapon", "诅咒武器" },
            { "Evil Omen", "邪恶预兆" },
            { "Horrific Beast", "恐怖野兽" },
            { "Lich Form", "巫妖形态" },
            { "Mind Rot", "心智腐烂" },
            { "Pain Spike", "痛苦尖刺" },
            { "Poison Strike", "毒击" },
            { "Strangle", "窒息" },
            { "Summon Familiar", "召唤魔宠" },
            { "Vampiric Embrace", "吸血鬼拥抱" },
            { "Vengeful Spirit", "复仇之魂" },
            { "Wither", "凋零" },
            { "Wraith Form", "幽灵形态" },
            { "Exorcism", "驱魔" },

            { "Cleanse By Fire", "火焰净化" },
            { "Close Wounds", "愈合伤口" },
            { "Consecrate Weapon", "奉献武器" },
            { "Dispel Evil", "驱散邪恶" },
            { "Divine Fury", "神圣狂怒" },
            { "Enemy Of One", "唯一之敌" },
            { "Holy Light", "圣光" },
            { "Noble Sacrifice", "高贵牺牲" },
            { "Remove Curse", "移除诅咒" },
            { "Sacred Journey", "神圣旅程" },

            { "Honorable Execution", "荣耀处决" },
            { "Confidence", "自信" },
            { "Evasion", "闪避" },
            { "Counter Attack", "反击" },
            { "Lightning Strike", "闪电一击" },
            { "Momentum Strike", "动量打击" },
            { "Focus Attack", "集中攻击" },
            { "Death Strike", "死亡打击" },
            { "Animal Form", "动物形态" },
            { "Ki Attack", "气功攻击" },
            { "Surprise Attack", "突袭" },
            { "Backstab", "背刺" },
            { "Shadow jump", "暗影跳跃" },
            { "Mirror Image", "镜像" },

            { "Arcane Circle", "奥术法阵" },
            { "Gift Of Renewal", "复苏之赐" },
            { "Immolating Weapon", "献祭武器" },
            { "Attunement", "协调" },
            { "Thunderstorm", "雷暴" },
            { "Natures Fury", "自然之怒" },
            { "Summon Fey", "召唤仙灵" },
            { "Summoniend", "召唤恶魔" },
            { "Reaper Form", "收割者形态" },
            { "Wildfire", "野火" },
            { "Essence Of Wind", "风之精华" },
            { "Dryad Allure", "树妖魅惑" },
            { "Ethereal Voyage", "虚灵旅程" },
            { "Word Of Death", "死亡之言" },
            { "Gift Of Life", "生命之赐" },
            { "Arcane Empowerment", "奥术强化" },

            { "Nether Bolt", "幽冥箭" },
            { "Purge Magic", "净化魔法" },
            { "Enchant", "附魔" },
            { "Sleep", "沉睡" },
            { "Eagle Strike", "鹰击" },
            { "Animated Weapon", "活化武器" },
            { "Stone Form", "石化形态" },
            { "Spell Trigger", "法术触发" },
            { "Mass Sleep", "群体沉睡" },
            { "Cleansing Winds", "净化之风" },
            { "Bombard", "轰击" },
            { "Spell Plague", "法术瘟疫" },
            { "Hail Storm", "冰雹风暴" },
            { "Nether Cyclone", "幽冥旋风" },
            { "Rising Colossus", "崛起巨像" },

            { "Inspire", "激励" },
            { "Invigorate", "振奋" },
            { "Resilience", "韧性" },
            { "Perseverance", "坚毅" },
            { "Tribulation", "磨难" },
            { "Despair", "绝望" },
            { "Death Ray", "死亡射线" },
            { "Ethereal Blast", "虚灵爆破" },
            { "Nether Blast", "幽冥爆破" },
            { "Mystic Weapon", "神秘武器" },
            { "Command Undead", "号令亡灵" },
            { "Conduit", "导流" },
            { "Mana Shield", "法力护盾" },
            { "Summon Reaper", "召唤收割者" },
            { "Enchanted Summoning", "强化召唤" },
            { "Anticipate Hit", "预判攻击" },
            { "Warcry", "战吼" },
            { "Intuition", "直觉" },
            { "Rejuvenate", "回春" },
            { "Holy Fist", "圣拳" },
            { "Shadow", "暗影" },
            { "White Tiger Form", "白虎形态" },
            { "Flaming Shot", "火焰射击" },
            { "Playing The Odds", "把握胜算" },
            { "Thrust", "突刺" },
            { "Pierce", "穿刺" },
            { "Stagger", "踉跄" },
            { "Toughness", "强韧" },
            { "Onslaught", "猛攻" },
            { "Focused Eye", "专注之眼" },
            { "Elemental Fury", "元素狂怒" },
            { "Called Shot", "精准射击" },
            { "Knockout", "击倒" },
            { "Saving Throw", "豁免" },
            { "Shield Bash", "盾击" },
            { "Bodyguard", "护卫" },
            { "Heighten Senses", "强化感知" },
            { "Tolerance", "耐受" },
            { "Injected Strike", "注能打击" },
            { "Potency", "效能" },
            { "Rampage", "狂暴" },
            { "Fists Of Fury", "狂怒之拳" },
            { "Boarding", "登船" },
            { "Combat Training", "战斗训练" },
            { "Whispering", "低语" },

            { "Target Self", "选择自己" },
            { "Target Last", "选择上个目标" },
            { "Target Self Queued", "排队选择自己" },
            { "Target Last Queued", "排队选择上个目标" },
            { "Target Cancel", "取消目标" },
            { "Clear Target Queue", "清空目标队列" },
            { "Clear Last Target", "清除上个目标" },
            { "Clear Last and Queue", "清除上个目标和队列" },
            { "Set Last", "设置上个目标" },
            { "Stop All", "停止全部脚本" },

            { "Compassion", "慈悲" },
            { "Honesty", "诚实" },
            { "Honor", "荣誉" },
            { "Humility", "谦逊" },
            { "Justice", "正义" },
            { "Sacrifice", "牺牲" },
            { "Valor", "英勇" }
        };

        internal static string Get(string name)
        {
            return m_names.TryGetValue(name, out string displayName) ? displayName : name;
        }
    }
}
